#!/bin/bash

# Title of the console
echo "Running $0"

# Check if the correct number of arguments are provided
required_args=5
if [ $# -lt $required_args ]; then
    echo "Usage: <username> <password> <database_connection_url> <database_user_name> <database_password>"
    exit 1
fi

SERVER_DIR=./target/server
MODULE_PATH="$SERVER_DIR/modules/system/layers/base/com/fasterxml/jackson/jakarta/jackson-jakarta-json-provider/main"
MODULE_FILE="$MODULE_PATH/module.xml"

if [ -d ./target/server ]; then
    # Run the server in background
    mvn wildfly:run -DskipTests -q &
    sleep 10

    # Fix the warning WFLYWELD0052
    echo '<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright The WildFly Authors
  ~ SPDX-License-Identifier: Apache-2.0
  -->
<module name="com.fasterxml.jackson.jakarta.jackson-jakarta-json-provider"
    xmlns="urn:jboss:module:1.9">
    <resources>
        <resource-root path="jackson-jakarta-rs-json-provider-2.15.2.jar" />
        <resource-root path="jackson-jakarta-rs-base-2.15.2.jar" />
        <resource-root path="jackson-module-jakarta-xmlbind-annotations-2.15.2.jar" />
    </resources>

    <dependencies>
        <module name="com.fasterxml.jackson.core.jackson-annotations" />
        <module name="com.fasterxml.jackson.core.jackson-core" />
        <module name="com.fasterxml.jackson.core.jackson-databind" />
        <module name="jakarta.ws.rs.api" />
        <module name="jakarta.xml.bind.api" />
        <module name="org.jboss.weld.core" />
        <module name="org.jboss.weld.spi" />
        <module name="org.jboss.weld.api" />
    </dependencies>
</module>' >"$MODULE_FILE"

    # Add user
    "$SERVER_DIR/bin/add-user.sh" -u "$1" -p "$2" -g admin

    # Download the driver
    curl -L -o mysql-connector-j-8.4.0.tar.gz https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-j-8.4.0.tar.gz
    tar -xvf mysql-connector-j-8.4.0.tar.gz
    mv mysql-connector-j-8.4.0/mysql-connector-j-8.4.0.jar "$SERVER_DIR/bin"
    rm -rf mysql-connector-j-8.4.0
    rm mysql-connector-j-8.4.0.tar.gz

    # Add the data source
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command="module add --name=com.mysql --resources=$SERVER_DIR/bin/mysql-connector-j-8.4.0.jar --dependencies=javax.api,javax.transaction.api"
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command="/subsystem=datasources/jdbc-driver=mysql:add(driver-name=mysql,driver-module-name=com.mysql,driver-class-name=com.mysql.cj.jdbc.Driver)"
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command="data-source add --name=database --jndi-name=jdbc/mysql --driver-name=mysql --connection-url=$3 --user-name=$4 --password=$5 --jta=true --use-java-context=true --use-ccm=true"
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command="/subsystem=datasources/data-source=database:write-attribute(name=enabled,value=true)"

    # Kill the process using port 8080
    fuser -k 8080/tcp

else
    echo "The server was not built yet. Run 'mvn clean install' first."
fi
