#!/bin/bash

# Title of the console
echo "Running $0"

# Check if the correct number of arguments are provided
required_args=5
if [ $# -lt $required_args ]; then
    echo "Usage: <username> <password> <database_connection_url> <database_user_name> <database_password>"
    exit 1
fi

SERVER_DIR=./target/server
MODULE_PATH="$SERVER_DIR/modules/system/layers/base/com/fasterxml/jackson/jakarta/jackson-jakarta-json-provider/main"
MODULE_FILE="$MODULE_PATH/module.xml"

if [ -d ./target/server ]; then
    # Run the server in background
    ./mvnw wildfly:run -Pproduction -DskipTests -q &
    sleep 50

    # Fix the warning WFLYWELD0052
    echo '<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright The WildFly Authors
  ~ SPDX-License-Identifier: Apache-2.0
  -->
<module name="com.fasterxml.jackson.jakarta.jackson-jakarta-json-provider"
    xmlns="urn:jboss:module:1.9">
    <resources>
        <resource-root path="jackson-jakarta-rs-json-provider-2.15.2.jar" />
        <resource-root path="jackson-jakarta-rs-base-2.15.2.jar" />
        <resource-root path="jackson-module-jakarta-xmlbind-annotations-2.15.2.jar" />
    </resources>

    <dependencies>
        <module name="com.fasterxml.jackson.core.jackson-annotations" />
        <module name="com.fasterxml.jackson.core.jackson-core" />
        <module name="com.fasterxml.jackson.core.jackson-databind" />
        <module name="jakarta.ws.rs.api" />
        <module name="jakarta.xml.bind.api" />
        <module name="org.jboss.weld.core" />
        <module name="org.jboss.weld.spi" />
        <module name="org.jboss.weld.api" />
    </dependencies>
</module>' >"$MODULE_FILE"

    # Add user
    "$SERVER_DIR/bin/add-user.sh" -u "$1" -p "$2" -g admin

    # Download the driver
    curl -L -o mysql-connector-j-8.4.0.tar.gz https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-j-8.4.0.tar.gz
    tar -xvf mysql-connector-j-8.4.0.tar.gz
    mv mysql-connector-j-8.4.0/mysql-connector-j-8.4.0.jar "$SERVER_DIR/bin"
    rm -rf mysql-connector-j-8.4.0
    rm mysql-connector-j-8.4.0.tar.gz

    # Add the data source
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command="module add --name=com.mysql --resources=$SERVER_DIR/bin/mysql-connector-j-8.4.0.jar --dependencies=javax.api,javax.transaction.api"
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command="/subsystem=datasources/jdbc-driver=mysql:add(driver-name=mysql,driver-module-name=com.mysql,driver-class-name=com.mysql.cj.jdbc.Driver)"
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command="data-source add --name=database --jndi-name=jdbc/mysql --driver-name=mysql --connection-url=$3 --user-name=$4 --password=$5 --jta=true --use-java-context=true --use-ccm=true --enabled=true --min-pool-size=10 --max-pool-size=30 --idle-timeout-minutes=5 --pool-prefill=true --pool-use-strict-min=true --query-timeout=4 --validate-on-match=true --background-validation=true --background-validation-millis=15000 --track-statements=NOWARN --new-connection-sql=\"SELECT 1\" --check-valid-connection-sql=\"SELECT 2\" --blocking-timeout-wait-millis=30000 --flush-strategy=FailingConnectionOnly"
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command='/subsystem=undertow/configuration=filter/response-header="Access-Control-Allow-Origin":add(header-name="Access-Control-Allow-Origin",header-value="*")'
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command='/subsystem=undertow/configuration=filter/response-header="Access-Control-Allow-Methods":add(header-name="Access-Control-Allow-Methods",header-value="GET, POST, OPTIONS, PUT, DELETE")'
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command='/subsystem=undertow/configuration=filter/response-header="Access-Control-Allow-Headers":add(header-name="Access-Control-Allow-Headers",header-value="*")'
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command='/subsystem=undertow/configuration=filter/response-header="Access-Control-Allow-Credentials":add(header-name="Access-Control-Allow-Credentials",header-value="true"'
    "$SERVER_DIR/bin/jboss-cli.sh" --connect --command='/subsystem=undertow/configuration=filter/response-header="Access-Control-Max-Age":add(header-name="Access-Control-Max-Age",header-value="3600")'

    # Kill the process using port 8080
    fuser -k 8080/tcp || echo "Port 8080 is not in use."

else
    echo "The server was not built yet. Run 'mvn clean install' first."
fi
